trigger:
  branches:
    include:
      - 'master'

pool: Default

variables:
  solution: '**/*.sln'
  functionProject: 'src/Football.Bot.AzureFunction'

steps:
- task: UseDotNet@2
  displayName: Use .NET6 to build
  inputs:
    version: '6.0.x'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(Build.SourcesDirectory)/$(functionProject)/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
  displayName: 'Build project'
- task: DotNetCoreCLI@2
  inputs:
    command: publish
    arguments: '--configuration $(buildConfiguration) --output publish_output'
    projects: '$(Build.SourcesDirectory)/$(functionProject)/*.csproj'
    publishWebProjects: false
    modifyOutputPath: false
    zipAfterPublish: false
  displayName: 'Publish project'

- task: ArchiveFiles@2
  displayName: "Archive files"
  inputs:
    rootFolderOrFile: "$(System.DefaultWorkingDirectory)/publish_output"
    includeRootFolder: false
    archiveFile: "$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip"

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip'
    artifactName: 'drop'
