name: Deploy DotNet project to Azure Function App

on:
  push:
    branches:
      - master

env:
  AZURE_FUNCTIONAPP_NAME: 'Football.Bot.AzureFunction' 
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'src/Football.Bot.AzureFunction'
  DOTNET_VERSION: '6.0.x'
  
jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet build --configuration Release --output ./output
        popd

    - name: Store artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: |
          '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
          
#    - name: 'Run Azure Functions Action'
#      uses: Azure/functions-action@v1
#      id: fa
#      with:
#        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
#        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
#        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }} # Remove publish-profile to use Azure RBAC
  deploy:
    needs: build_test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, stage]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts
          path: |
            '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'

      - name: Deploy to ${{ matrix.environment }}
        uses: Azure/functions-action@v1
        with:
          app-name: myapp-${{ matrix.environment }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
